// vite-project/src/views/About.vue
<template>
	<div>
		<div class="q-py-md text-h4">
			About this app
		</div>
		<div class="flex-center">
			This app is developed by <a href="https://allandrozd.com/" target="_blank" class="text-weight-bold"
				style="text-decoration: none">Allan Drozd</a>
		</div>
	</div>
</template>

<script setup>
import { useHead } from "@vueuse/head";

useHead({
	title: 'P2P - Playstation To PC'
})
</script>

// react-project/src/pages/about.jsx
import React from "react";
import {Box, Text, Link} from "@chakra-ui/react";

export default function About() {
    return (
    <Box align={'center'}>
        <Text fontSize={{ base: '2xl', md:'3xl' }}>
           About this app
        </Text>
        <Text mt="5">
            This app is developed by <Link href="https://allandrozd.com/" isExternal fontWeight='bold'>Allan Drozd</Link>
        </Text>
    </Box>
    );
}
