// vite-project/src/views/Home.vue
<template>
  <div>
    <div class="q-py-md text-h4">
      These are the games that went from playstation consoles to PC
    </div>
    <div class="row justify-center q-gutter-md q-mx-none">
      <q-card v-for="game in results" flat bordered style="width: 310px">
        <q-card-section class="text-weight-bold">
          {{ game.attributes.title }}
        </q-card-section>
        <q-card-section class="q-pa-none">
          <q-img width="200px"
                 :src="`http://localhost:1337${game.attributes.image.data.attributes.formats.small.url}`"/>
        </q-card-section>
        <q-card-section class="lineClamp">
          {{ game.attributes.description }}
        </q-card-section>
        <q-card-section>
          <q-btn color="primary" unelevated no-caps class="text-weight-bold" :to="`/game/${game.id}`">Read more</q-btn>
        </q-card-section>
      </q-card>
    </div>
  </div>
</template>
<script setup lang="ts">
import {ref, onBeforeMount} from 'vue'
import shave from "shave";

const api = import.meta.env.VITE_API_URL;

const name: string = 'Allan';
const results = ref(null);

onBeforeMount(() => {
  console.log(api + '/games');
  fetch(api + '/games?fields=title,description&populate=image&sort=pcReleaseDate:desc').then((response) => response.json()).then((data) =>
      results.value = data.data);
})
</script>

<style>
.lineClamp {
  height: 300px;
  overflow: hidden;
  display: -webkit-box;
  -webkit-line-clamp: 6;
  -webkit-box-orient: vertical;
}
</style>

// react-project/src/pages/home.jsx
import React from "react";
import {Box, Button, HStack, Image, Skeleton, SkeletonText, Text, Wrap, WrapItem} from "@chakra-ui/react";
import {Link} from "react-router-dom";
import GameSkeleton from "../components/gameSkeleton";

export default function Home() {

    class GameGrid extends React.Component {
        constructor(props) {
            super(props);
            this.state = {
                error: null, isLoaded: false, items: []
            };
        }

        componentDidMount() {
            fetch("http://localhost:1337/api/games?fields=title,description&populate=image&sort=pcReleaseDate:desc")
                .then(res => res.json())
                .then((result) => {
                    this.setState({
                        isLoaded: true, items: result.data
                    });
                }, (error) => {
                    this.setState({
                        isLoaded: true, error
                    });
                })
        }

        render() {
            const {error, isLoaded, items} = this.state;
            if (error) {
                return <div>Error: {error.message}</div>;
            } else if (!isLoaded) {
                return (
                    <GameSkeleton />
                );
            } else {
                return (
                    <Wrap spacing={6} m='6' justify="center">
                    {items.map(item => (
                        <WrapItem maxW='sm' borderWidth='1px' borderRadius='lg' overflow='hidden' key={item.id}>
                            <Box p='2'>
                                <Box mt='3' fontWeight='semibold' as='h4' lineHeight='tight' noOfLines={1}>
                                    {item.attributes.title}
                                </Box>
                                <Box my="3" align="center">
                                    <Image borderRadius="md" boxSize="200" objectFit="cover" src={`http://localhost:1337${item.attributes.image.data.attributes.formats.small.url}`} />
                                </Box>
                                <Box>
                                    <Text noOfLines={6}>
                                        {item.attributes.description}
                                    </Text>
                                </Box>
                                <Box py="3">
                                    <Link to={`details/${item.id}`}><Button>Read more</Button></Link>
                                </Box>
                            </Box>
                        </WrapItem>))}
                </Wrap>
                );
            }
        }
    }

    return (<div>
        <Text fontSize="2xl">
        These are the games that went from playstation consoles to PC
        </Text>
        <GameGrid />
    </div>);
}
